title: Jay Johnson
description: Personal blog featuring technology projects, home improvement guides, and technical insights. Documenting hands-on projects and software development experiences.
url: "https://nordhus.site"
markdown: kramdown
permalink: /blog/:title/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Analytics
google_analytics: G-5KRKCPHCGX

# Production-safe defaults

# Include files that should be copied as-is
include:
  - favicon.ico

# Exclude files from processing to speed up builds
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .tmp/
  - Makefile
  - Dockerfile
  - docker-compose.yml
  - README.md
  - scripts/
  - tests/
  - .git/
  - .github/
  - .gitignore
  - .dockerignore
  - "*.log"
  - "*.py"
  - "*.pyc"
  - pyproject.toml
  - __pycache__/
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/