title: Jay Johnson
description: Personal website and blog
url: "https://nordhus.site"
markdown: kramdown
permalink: /blog/:title/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Production-safe defaults

# Include files that should be copied as-is
include:
  - favicon.ico

# Exclude files from processing to speed up builds
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .tmp/
  - Makefile
  - Dockerfile
  - docker-compose.yml
  - README.md
  - scripts/
  - .git/
  - .github/
  - .gitignore
  - .dockerignore
  - "*.log"
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/