[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# Also enable isort (`I`), pep8-naming (`N`), and pyupgrade (`UP`) for comprehensive checking
lint.select = ["E", "F", "I", "N", "UP", "W", "B", "A", "C4", "T20", "SIM", "ARG", "PTH", "PLE", "PLR", "PLW", "TRY", "RUF"]

# Allow fix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []

# Exclude common directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "_site",
    ".jekyll-cache"
]

# Set line length to be more lenient  
line-length = 150

# Allow unused variables when underscore-prefixed
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore specific rules that are too strict for this codebase
lint.ignore = [
    "TRY002",  # Create your own exception - too strict for this use case
    "TRY003",  # Avoid long messages in exceptions - too strict
    "PTH103",  # os.makedirs vs Path.mkdir - mixed usage is OK
    "PTH123",  # open() vs Path.open() - mixed usage is OK
    "ARG001",  # Unused function argument - common in callback patterns
    "ARG002",  # Unused method argument - common in interface implementations
    "PLR1722", # Use sys.exit instead of exit - exit() is fine in scripts
    "SIM108",  # Use ternary operator - readability preference
    "SIM117",  # Use single with statement - readability preference
    "TRY300",  # Consider moving to else block - not always clearer
    "F841",    # Local variable assigned but never used - common in test setup
    "W293",    # Blank line contains whitespace - minor formatting
    "W291",    # Trailing whitespace - minor formatting  
    "PTH109",  # os.getcwd vs Path.cwd - mixed usage is OK
    "PTH118",  # os.path.join vs Path - mixed usage is OK 
    "PTH120",  # os.path.dirname vs Path.parent - mixed usage is OK
    "PLR2004", # Magic value used in comparison - too strict
    "RUF013",  # PEP 484 implicit optional - too strict for this project
    "RUF001",  # Ambiguous unicode characters - emojis are intentional
    "PLR0913"  # Too many arguments - acceptable for constructors
]

# Assume Python 3.8+
target-version = "py38"

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.isort]
# Use single line imports
force-single-line = true

[tool.ruff.lint.per-file-ignores]
# Tests can use assert statements but should catch unused imports
"tests/*" = ["B011"]

# Scripts may use print statements
"scripts/*" = ["T201"]

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces, not tabs
indent-style = "space"

# Respect magic trailing commas
skip-magic-trailing-comma = false

# Automatically detect line endings
line-ending = "auto"