name: Construction Project Monitor
on:
  schedule:
    - cron: '0 0 * * *'  # Every 24 hours at midnight UTC
  workflow_dispatch:     # Manual trigger
  push:
    branches: [ main ]   # Only run on main branch pushes
  
env:
  PYTHON_VERSION: '3.11'
  ENABLE_PHOTO_MONITORING: 'true'  # Feature flag: set to 'true' to enable photo album integration

jobs:
  monitor-projects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for branch operations
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ruff python-dotenv cloudinary
        
    - name: Check code quality
      run: |
        echo "Running quick linter check..."
        ruff check scripts/ --select=E,F,W --quiet
        
    - name: Configure git
      run: |
        git config --global user.name "Construction Bot"
        git config --global user.email "noreply@nordhus.site"
        
    - name: Monitor Construction Projects
      if: env.ENABLE_PHOTO_MONITORING == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
      run: |
        echo "Checking for construction project updates..."
        if ! PYTHONPATH=scripts python scripts/workflows/construction_monitor.py; then
          echo "❌ Construction project monitoring failed"
          exit 1
        fi
        echo "✅ Construction project monitoring completed successfully"
      
    - name: Photo monitoring disabled
      if: env.ENABLE_PHOTO_MONITORING != 'true'
      run: |
        echo "Photo album monitoring is currently disabled"
        echo "To enable, set ENABLE_PHOTO_MONITORING to 'true' in the workflow file"
      
    - name: Push changes if any
      if: env.ENABLE_PHOTO_MONITORING == 'true'
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "Changes detected, pushing to repository"
          git push origin HEAD
        else
          echo "No changes to push"
        fi